### ISSUE TITLE
400 Error while performing curl request 

### ISSUE THREAD

**Issue by avicoder** [rare-magma/cloudflare-exporter#1]
Hi

this error is thrown when running the script indie the docker and as a standalone 

`curl: (22) The requested URL returned error: 400`

not sure if we are passing the headers in curl correctly.
could you please help

**Comment by rare-magma** [comment]
hi, a 400 error code means you probably have an issue with the [cloudflare_exporter.conf](https://github.com/rare-magma/cloudflare-exporter/blob/main/cloudflare_exporter.conf) or [cloudflare_zone_list.json](https://github.com/rare-magma/cloudflare-exporter/blob/main/cloudflare_zone_list.json) files. 
Please make sure they are setup correctly.

**Comment by avicoder** [comment]
No, it was not related to this.

turns out I'd to add these two headers in the cloudflare_exporter.sh script to make it work
```
  -H "X-Auth-Email: cf_email@example.com" \
  -H 'Authorization: Bearer CF_API_TOKEN' \
```

script needs modification.

**Comment by rare-magma** [comment]
@avicoder is the cloudflare account that you are using in a paid plan?  I think if that is the case it might be required to add that header.
I've added support for it on https://github.com/rare-magma/cloudflare-exporter/commit/917001df3eb2383ba537af592e006041785a2bc9

**Comment by avicoder** [comment]
yeah, it's pro plan

**Comment by rare-magma** [comment]
@avicoder does the exporter work for you with the latest change on https://github.com/rare-magma/cloudflare-exporter/commit/917001df3eb2383ba537af592e006041785a2bc9?
